import { useState } from "react";
import TabContent from "./TabContent";
import tab1 from '../assets/Images/chatroom.png';
import tab2 from '../assets/Images/tab-1.png';
import tab3 from '../assets/Images/video.png';
import tab4 from '../assets/Images/image.png';
import tab5 from '../assets/Images/assistant.png';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/swiper-bundle.css';

const Tab = () => {
    const [toggle, setToggle] = useState(1)
    console.log(toggle);

    return (
        <div role="tablist" className=" md:mx-5 mt-10 pt-6 text-center h-[1100px] md:h-[1250px] lg:h-[950px]">
            <Swiper
             breakpoints={{
                // When window width is >= 640px (small devices)
                300: {
                  slidesPerView: 2,
                },
                // When window width is >= 768px (medium devices)
                768: {
                  slidesPerView: 4,
                },
                // When window width is >= 1024px (large devices)
                1024: {
                  slidesPerView: 5,
                },
              }}
                spaceBetween={0}
                slidesPerView={'auto'}
                centeredSlides={false}
                grabCursor={true}
                className="w-full"
            >
                <SwiperSlide className="">
                    <button onClick={() => setToggle(1)} className={`w-[170px] md:w-[170px] lg:w-[255px] text-center py-4 text-base lg:text-xl font-semibold rounded-lg hover:bg-[#2d9f89] ${toggle === 1 ? "text-white" : "text-[#a1a3ab]"} hover:text-white ${toggle === 1 ? "bg-[#2d9f89]" : "bg-[#0a101f]"}`}>Chatroom</button>
                </SwiperSlide>
                <SwiperSlide className="">
                    <button onClick={() => setToggle(2)} className={`w-[170px] md:w-[170px] lg:w-[255px] text-center py-4 text-base lg:text-xl font-semibold rounded-lg hover:bg-[#2d9f89] ${toggle === 2 ? "text-white" : "text-[#a1a3ab]"} hover:text-white ${toggle === 2 ? "bg-[#2d9f89]" : "bg-[#0a101f]"}`}>Youtube Translation</button>
                </SwiperSlide>
                <SwiperSlide className="">
                    <button onClick={() => setToggle(3)} className={`w-[170px] md:w-[170px] lg:w-[255px] text-center py-4 text-base lg:text-xl font-semibold rounded-lg hover:bg-[#2d9f89] ${toggle === 3 ? "text-white" : "text-[#a1a3ab]"} hover:text-white ${toggle === 3 ? "bg-[#2d9f89]" : "bg-[#0a101f]"}`}>AI Video Subtitles</button>
                </SwiperSlide>
                <SwiperSlide className="">
                    <button onClick={() => setToggle(4)} className={`w-[170px] md:w-[170px] lg:w-[255px] text-center py-4 text-base lg:text-xl font-semibold rounded-lg hover:bg-[#2d9f89] ${toggle === 4 ? "text-white" : "text-[#a1a3ab]"} hover:text-white ${toggle === 4 ? "bg-[#2d9f89]" : "bg-[#0a101f]"}`}>Images Generation</button>
                </SwiperSlide>
                <SwiperSlide className="mr-4">
                    <button onClick={() => setToggle(5)} className={`w-[170px] md:w-[170px] lg:w-[255px] text-center py-4 text-base lg:text-xl font-semibold rounded-lg hover:bg-[#2d9f89] ${toggle === 5 ? "text-white" : "text-[#a1a3ab]"} hover:text-white ${toggle === 5 ? "bg-[#2d9f89]" : "bg-[#0a101f]"}`}>AI Assistant</button>
                </SwiperSlide>
            </Swiper>

            <div className="mb-48 mt-20">
                <div className={`${toggle !== 1 ? "hidden" : "block"} h-[500px] w-full text-center font-semibold text-2xl  `}>
                    <TabContent
                        title={'Connect Globally with AI-Powered Chatroom'}
                        subTitle={'Connect globally with our Chatroom feature, using AI translation for seamless and meaningful conversations.'}
                        feature1={'Chat with people worldwide in your native language.'}
                        feature2={'Utilize AI-powered translation for smooth communication.'}
                        image={tab1}
                    /></div>
                <div className={`${toggle !== 2 ? "hidden" : "block"} h-[500px] w-full text-center font-semibold text-2xl  `}>
                    <TabContent
                        title={'Transformative AI Elevating Videos with Automated Subtitling'}
                        subTitle={'Step into the realm of cutting-edge video enhancement with our AI-driven subtitle tool, revolutionizing content accessibility.'}
                        feature1={'Empower your content with accurate and timely subtitles, effortlessly generated by advanced AI algorithms.'}
                        feature2={'Enhance viewer retention and comprehension by providing subtitles in multiple languages, facilitated by automated translation.'}
                        image={tab2}
                    /></div>
                <div className={`${toggle !== 3 ? "hidden" : "block"} h-[500px] w-full text-center font-semibold text-2xl  `}>
                    <TabContent
                        title={'Revolutionize Accessibility with AI Video Subtitles'}
                        subTitle={'Revolutionize your video accessibility with AI-driven subtitle generation, offering seamless and accurate subtitling.'}
                        feature1={'Generate accurate Mongolian subtitles automatically with advanced AI.'}
                        feature2={'Improve video accessibility and engagement.'}
                        image={tab3}
                    /></div>
                <div className={`${toggle !== 4 ? "hidden" : "block"} h-[500px] w-full text-center font-semibold text-2xl  `}>
                    <TabContent
                        title={'Create Stunning Visuals with Image Generation'}
                        subTitle={'Create stunning visuals effortlessly with our AI-powered Image Generation tool, bringing your creative ideas to life.'}
                        feature1={'Produce high-quality images based on your prompts.'}
                        feature2={'Visualize your ideas with the help of AI.'}
                        image={tab4}
                    /></div>
                <div className={`${toggle !== 5 ? "hidden" : "block"} h-[500px] w-full text-center font-semibold text-2xl  `}>
                    <TabContent
                        title={'Enhance Productivity with AI Assistant'}
                        subTitle={'Enhance your productivity with our AI Assistant, offering smart, efficient help and internet search in Mongolian.'}
                        feature1={'Get accurate answers and perform tasks with AI assistance.'}
                        feature2={'Access relevant search results in Mongolian.'}
                        image={tab5}
                    /></div>
            </div>
        </div>
    );
};

export default Tab;